### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16

### ISSUE THREAD

**Issue by soluml** [Originate/react-e#15]
I'm getting the following warning in Spaceful's console when running the app:

> React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, [create-react-class](https://www.npmjs.com/package/create-react-class) is available on npm as a drop-in replacement.

It looks like react-e needs to be updated to support version 16.

**Comment by alexdavid** [comment]
Are you sure this is an issue with `react-e`? This codebase does not use `React.createClass` at all.
