### ISSUE TITLE
usage with css modules

### ISSUE THREAD

**Issue by charlierudolph** [Originate/react-e#3]
Feels a little less than ideal. Maybe worth adding in a special case or another function where you can pass in just a class name.

``` coffeescript
classNames = require './index.styl'
e = require 'react-e'

#...

  render: ->
    e ".#{classNames.root}",
      e ".#{classNames.title}", 'My Todo List'
      e ".#{classNames.links}",
        # ...
```

**Comment by alexdavid** [comment]
Yeah, this isn't great. What about something like this:

``` coffeescript
classNames = require './index.styl'
e = require('react-e/bind')(classNames)

#...

  render: ->
    e '.root',
      e '.title', 'My Todo List'
      e '.links',
```

It can just run all classnames through `classnames/bind`. We can add a special prop for global classnames since I think 99% of usecases will use local ones

``` coffeescript
e '.root', className: 'another-local-classname', globalClassName: 'something-global'
```

**Comment by charlierudolph** [comment]
Sounds like an awesome idea. I don't know if global classnames needs to be separate and if it doesn't match it just assumes global. Are you planning on throwing an error if the className isn't bound? If so, could possibly just pass in globals separately with something like:

``` coffee
e = require('react-e/bind')(classNames, globalClassNames: ['something-global']
```

**Comment by alexdavid** [comment]
Oh yeah I hadn't thought about checking to see if the class exists on the object. 

However one issue is it isn't immediately obvious from looking at the render method if a class will be a global or a local class. Might not be an issue though

**Comment by charlierudolph** [comment]
I'd say lets go with your initial suggestion where we add support for `globalClassName` as a prop you can pass to `e`. I'd still like an error thrown for unbound local classes when using `bind`. I'll take a shot at implementing this
