### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by alexdavid** [Originate/react-e#4]
@rossfoley mentioned that the error he gets when forgetting a `.` before the class is cryptic. We should throw a good error if you attempt to create an element that doesn't exist on `react.DOM`

**Comment by sleexyz** [comment]
I sometimes accidentally keep the `e` in when I switch from an e component to a create-factory'ed component.

Like I start with:
```
e 'div'
```
as a placeholder, and then switch to

```
e FooComponent
```

which gives me cryptic errors. It would be nice if either
1. e had support for component factories in that position, don't know what that would look like/if it would be nice either way
2. e threw an useful error telling me that I probably accidentally put a component factory there

**Comment by alexdavid** [comment]
👍 I think it would be cool if you could use e even with non-factories and it calls `react.createElement` on it much like how JSX does it. This would also be good for binding for components that take in a `className` prop, we could automatically convert it.

**Comment by sleexyz** [comment]
hmm yeah in that case, I'm imagining a hypothetical setup where e would be used *exclusively* to deal with raw Components. That would be quite nice...

So in this hypothetical setup, we would never have to use `create-factory-loader`, for example. `e` everywhere!

One feature I'd rather not have as a library user is the ability to support both raw Components and factories; that would just be confusing to see in a codebase.

**Comment by alexdavid** [comment]
Agreed, yeah I see it as taking the place of `create-factory-loader`
